version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      prisma-orm:
        applies-to: version-updates
        patterns:
          - "prisma"
          - "@prisma/client"
      prisma-security:
        applies-to: security-updates
        patterns:
          - "prisma"
          - "@prisma/client"
